### ISSUE TITLE
Strange behavior when using Golang 1.4.2

### ISSUE THREAD

**Issue by calebamiles** [cloudfoundry-incubator/candiedyaml#9] opened 2015-04-09 16:58 UTC
Hello,

We were seeing some strange behavior when trying to unmarshal the release manifest when using a binary built with Golang 1.4.2. The following release manifest (release.MF inside a BOSH release)

```yaml
---
packages:
- name: bosh_aws_cpi
  version: 2bb22c5a553350eed303a5382d4d557798d48914
  fingerprint: 2bb22c5a553350eed303a5382d4d557798d48914
  sha1: 0910f53d9a2d39586524c62db6daaafed286b754
  dependencies:
  - ruby_aws_cpi
- name: ruby_aws_cpi
  version: 052a28b8976e6d9ad14d3eaec6d3dd237973d800
  fingerprint: 052a28b8976e6d9ad14d3eaec6d3dd237973d800
  sha1: 714721b012d5595fe82ea9b4d3249ec8b81f1111
  dependencies: []
jobs:
- name: cpi
  version: ca1bbc783f6b12eb1d066ac4b54c75fb8351465e
  fingerprint: ca1bbc783f6b12eb1d066ac4b54c75fb8351465e
  sha1: 691b21147d13b96848f1e66a8d14260eebc12527
commit_hash: 5a4f720e
uncommitted_changes: true
name: bosh-aws-cpi
version: '6'
```

fails to unmarshal the `Version` field into the following struct

```go
type Manifest struct {
        Name    string `yaml:"name"`
        Version string `yaml:"version"`

        CommitHash         string `yaml:"commit_hash"`
        UncommittedChanges bool   `yaml:"uncommitted_changes"`

        Jobs     []JobRef     `yaml:"jobs"`
        Packages []PackageRef `yaml:"packages"`
}
```

We see this failure pretty repeatably and to reproduce you can follow the instructions for the [bosh micro CLI](https://github.com/cloudfoundry/bosh-micro-cli) with any release from [bosh hub](bosh.io). If you're not ready for Golang 1.4.2 support then we'll take a note of that and adjust our workstation environments accordingly.

Thanks!

@calebamiles
Pivotal CF BOSH Team

**Comment by fraenkel** [comment] 2015-04-10 02:51
Are you sure you are using the latest version from this repo?
It looks right to me....

<candiedyaml.Manifest>: {
            Name: "bosh-aws-cpi",
            Version: "6",
            CommitHash: "5a4f720e",
            UncommittedChanges: true,
            Jobs: [
                {
                    Name: "cpi",
                    Version: "ca1bbc783f6b12eb1d066ac4b54c75fb8351465e",
                    Fingerprint: "ca1bbc783f6b12eb1d066ac4b54c75fb8351465e",
                    Sha1: "691b21147d13b96848f1e66a8d14260eebc12527",
                },
            ],
            Packages: [
                {
                    Name: "bosh_aws_cpi",
                    Version: "2bb22c5a553350eed303a5382d4d557798d48914",
                    Fingerprint: "2bb22c5a553350eed303a5382d4d557798d48914",
                    Sha1: "0910f53d9a2d39586524c62db6daaafed286b754",
                    Dependencies: ["ruby_aws_cpi"],
                },
                {
                    Name: "ruby_aws_cpi",
                    Version: "052a28b8976e6d9ad14d3eaec6d3dd237973d800",
                    Fingerprint: "052a28b8976e6d9ad14d3eaec6d3dd237973d800",
                    Sha1: "714721b012d5595fe82ea9b4d3249ec8b81f1111",
                    Dependencies: [],
                },
            ],
        }

**Comment by fraenkel** [comment] 2015-04-12 00:46
@calebamiles Can you verify you are using the latest version from this repo?

**Comment by calebamiles** [comment] 2015-04-14 15:49
@fraenkel, according to godeps we're currently on 884e358e25b53c57d4717ca0791306adb174add1. I'll bump candiedyaml and move back to golang 1.4.2 and try again. Thanks!

**Comment by mariash** [comment] 2015-04-21 23:10
@fraenkel we cannot reproduce this any more, please feel free to close this issue.

**Closed by mariash** 2015-04-21 23:10 UTC
